spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/ootw
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
minio:
  url: http://localhost:9099
  bucket: ootw-bucket
  access-key: IamUser
  secret-key: IamPassword
jwt:
  issuer: ootw
  base64-secret:
  token-validity-in-seconds: 86400 # 24 * 60 * 60
server:
  port: 8080
forecast:
  service-key:
